### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

## Preprocessing the data

### Importing the dataset

In [3]:
dataset=pd.read_excel("Folds5x2_pp.xlsx")
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [4]:
dataset.isnull().values.any()

False

In [5]:
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [6]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [7]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X, y, test_size = 0.2, random_state=1)

##  Building the ANN Model

### Initializing the ANN

In [9]:
ann=tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the second hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the output layer

In [12]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [13]:
ann.compile(optimizer='adam',loss='mean_squared_error')

### Training the ANN on the Training set

In [14]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 5260.1314
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 247.0791
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 215.0442
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 193.0118
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 157.4941
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 128.1797
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 93.4084
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 35.0106
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 27.8929
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 27.2505
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 27.4617
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - loss: 27

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [15]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[454.1  458.96]
 [462.17 463.29]
 [438.18 435.27]
 ...
 [478.67 476.22]
 [428.01 440.29]
 [465.52 467.92]]


In [16]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9260072157385661