# Polynomial Regression

## Importing the libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [3]:
dataset = pd.read_csv('tested.csv')
X = dataset.iloc[:, 2:].values
y = dataset.iloc[:, 1].values

In [4]:
print(X)

[[3 'Kelly, Mr. James' 'male' ... 7.8292 nan 'Q']
 [3 'Wilkes, Mrs. James (Ellen Needs)' 'female' ... 7.0 nan 'S']
 [2 'Myles, Mr. Thomas Francis' 'male' ... 9.6875 nan 'Q']
 ...
 [3 'Saether, Mr. Simon Sivertsen' 'male' ... 7.25 nan 'S']
 [3 'Ware, Mr. Frederick' 'male' ... 8.05 nan 'S']
 [3 'Peter, Master. Michael J' 'male' ... 22.3583 nan 'C']]


In [5]:
print(y)

[0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 1 0 0 1 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 1
 1 0 0 0 0 0 1 1 0 0 0 1 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 1 1 0 0 1 1 0 1 0
 1 0 0 1 0 1 0 0 0 0 0 0 1 1 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0
 1 1 1 1 0 0 1 0 1 1 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0
 0 0 1 0 0 1 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0 1 1 0 1 1 0 0 1 0 1
 0 1 0 1 0 0 0 0 0 0 0 0 1 0 1 1 0 0 1 0 0 1 0 1 0 0 0 0 1 1 0 1 0 1 0 1 0
 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 1
 0 0 0 1 1 0 0 0 0 1 0 0 0 1 1 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0
 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0
 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 0 1 1 0 1 1 0
 0 1 0 0 1 1 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0
 0 1 1 1 1 1 0 1 0 0 0]


In [6]:
X=np.delete(X,1,1)

In [7]:
X=np.delete(X,5,1)

In [8]:
X=np.delete(X,6,1)

In [9]:
print(X)

[[3 'male' 34.5 ... 0 7.8292 'Q']
 [3 'female' 47.0 ... 0 7.0 'S']
 [2 'male' 62.0 ... 0 9.6875 'Q']
 ...
 [3 'male' 38.5 ... 0 7.25 'S']
 [3 'male' nan ... 0 8.05 'S']
 [3 'male' nan ... 1 22.3583 'C']]


In [10]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,2:6])
X[:,2:6] = imputer.transform(X[:,2:6])

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])] ,remainder='passthrough')
X =np.array(ct.fit_transform(X))

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [7])] ,remainder='passthrough')
X =np.array(ct.fit_transform(X))

In [13]:
print(X)

[[0.0 1.0 0.0 ... 0.0 0.0 7.8292]
 [0.0 0.0 1.0 ... 1.0 0.0 7.0]
 [0.0 1.0 0.0 ... 0.0 0.0 9.6875]
 ...
 [0.0 0.0 1.0 ... 0.0 0.0 7.25]
 [0.0 0.0 1.0 ... 0.0 0.0 8.05]
 [1.0 0.0 0.0 ... 1.0 1.0 22.3583]]


## Splitting the dataset into the Training set and Test set

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Polynomial Regression model on the Training set

In [15]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

LinearRegression()

## Predicting the Test set results

In [16]:
y_pred = regressor.predict(poly_reg.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 2.84e-01  0.00e+00]
 [-4.65e-08  0.00e+00]
 [ 1.00e+00  1.00e+00]
 [-1.52e-07  0.00e+00]
 [ 1.00e+00  1.00e+00]
 [-8.49e-05  0.00e+00]
 [ 1.00e+00  1.00e+00]
 [-6.02e-08  0.00e+00]
 [ 2.60e-03  0.00e+00]
 [-7.17e-08  0.00e+00]
 [ 1.00e+00  1.00e+00]
 [ 1.00e+00  1.00e+00]
 [ 7.78e-07  0.00e+00]
 [-9.54e-08  0.00e+00]
 [-1.10e-07  0.00e+00]
 [-6.59e-08  0.00e+00]
 [ 1.00e+00  1.00e+00]
 [-1.29e-07  0.00e+00]
 [ 1.00e+00  1.00e+00]
 [ 1.43e+00  1.00e+00]
 [-9.13e-08  0.00e+00]
 [ 1.00e+00  1.00e+00]
 [-3.66e-08  0.00e+00]
 [ 7.92e-08  0.00e+00]
 [ 1.46e-02  0.00e+00]
 [ 6.96e-07  0.00e+00]
 [ 1.00e+00  1.00e+00]
 [-1.13e-07  0.00e+00]
 [-6.06e-08  0.00e+00]
 [-1.00e-07  0.00e+00]
 [ 1.00e+00  1.00e+00]
 [ 1.00e+00  1.00e+00]
 [ 1.00e+00  1.00e+00]
 [ 1.02e+00  1.00e+00]
 [ 1.00e+00  1.00e+00]
 [ 1.44e-07  0.00e+00]
 [ 2.01e-03  0.00e+00]
 [ 1.00e+00  1.00e+00]
 [ 1.00e+00  1.00e+00]
 [ 9.99e-01  1.00e+00]
 [ 1.02e+00  1.00e+00]
 [-4.04e-08  0.00e+00]
 [ 1.00e+00  1.00e+00]
 [ 1.00e+00

## Evaluating the Model Performance

In [17]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9870884360630344